
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/LenovoPC/Documents/Luigi UCSP/LabCompiler2023_II_CG/Cmake/cmake-3.27.1-windows-x86_64/share/cmake-3.27/Modules/CMakeDetermineSystem.cmake:211 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The system is: Windows - 10.0.19045 - AMD64
...
